---
Name: commentroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    # handle old 2.4 style urls
    'CommentingController//$Action/$ID/$OtherID': 'CommentingController'
    'PageComments/$Action/$ID/$OtherID': 'CommentingController'
    'PageComments_Controller/$Action/$ID/$OtherID': 'CommentingController'